name: Cureface
favicon: null
layout_spectrum: 0.9259500324260443
typography_spectrum: 0.04621215956285596
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.30590772931464016
  lightness: 0.26250256365165114
  saturation: 0.9041376158129424
  rhythmicContrast: 0.5186002813279629
purpose: []
