name: Cureface
favicon: null
layout_spectrum: 0.90453
typography_spectrum: 0.76571
title: 'Cureface – Design Connected Experiences '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-67115013-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#25252d'
    - '#ebebe9'
    - '#b4c2c5'
    - '#97a7a6'
    - '#5f4c47'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
