typography_spectrum: 0.76571
color:
  brandColors:
    - '#cdd1da'
    - '#62737c'
    - '#040605'
    - '#f9c32d'
    - '#1d2b2e'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.5625
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.8244
analytics:
  google: UA-67115013-1
  facebook: null
  twitter: null
name: Cureface
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About me
    id: 91dd537f-b516-42c2-8d83-49a1d9979b3f
    type: content
favicon: null
title: Cureface
purpose: []
