name: Cureface
favicon: null
layout_spectrum: 0.8244
typography_spectrum: 0.76571
title: 'Cureface – Design Connected Experiences '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-67115013-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cdd1da'
    - '#62737c'
    - '#040605'
    - '#f9c32d'
    - '#1d2b2e'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
